##----- Kaiser Causal TTE-TND
##----- Simulation study 2: publication artifacts (MULTIPLICATIVE case only)
##----- Reads sim_eqc_pci_results.rds and writes multiplicative-only:
##-----   tab_eqc_pci_mult.tex   (booktabs)
##-----   fig_eqc_pci_mult.{png,pdf}
##----- Usage:  Rscript code/scripts/sim/sim_eqc_pci_report.R


library(data.table)

here  <- tryCatch(dirname(sys.frame(1)$ofile), error = function(e) "code/scripts/sim")
res   <- readRDS(file.path(here, "sim_eqc_pci_results.rds"))
long  <- as.data.table(res$long)[dgp == "multiplicative"]
n_rep <- res$n_rep
truth <- long$truth[1]

scen     <- c("eqc_holds", "eqc_violated")
meth_ord <- c("naive", "eqc", "pci")
scen_lab <- c(eqc_holds = "Equi-confounding holds", eqc_violated = "Equi-confounding violated")
meth_lab <- c(naive = "Naive (no de-biasing)", eqc = "Equi-confounding", pci = "Proximal (PCI)")
long[, method := factor(method, meth_ord)]
long[, scenario := factor(scenario, scen)]

summ <- long[, .(
  mean = mean(b2A), bias = mean(b2A - truth), se = sd(b2A), rmse = sqrt(mean((b2A - truth)^2))
), by = .(scenario, method)][order(scenario, method)]


# LaTeX table -------------------------------------------------------------


fnum <- function(x, d = 3) formatC(x, format = "f", digits = d)
con <- file(file.path(here, "tab_eqc_pci_mult.tex"), "w")
writeLines(c(
  "% Auto-generated by sim_eqc_pci_report.R",
  "\\begin{table}[t]", "\\centering",
  sprintf("\\caption{Recovery of the causal log hazard-ratio $\\beta_{2A}$ (true value $%s$) over %d replications, when equi-confounding holds and when it is violated. The proximal estimator, which relies on the negative control exposure rather than equi-confounding, remains near-unbiased under violation; the equi-confounding estimator does not.}",
          fnum(truth, 2), n_rep),
  "\\label{tab:sim_eqc_pci}",
  "\\begin{tabular}{llrrrr}", "\\toprule",
  "Scenario & Method & Mean & Bias & SE & RMSE \\\\", "\\midrule"), con)
for (s in scen) {
  sub <- summ[scenario == s]
  for (i in seq_len(nrow(sub))) {
    lead <- if (i == 1) scen_lab[[s]] else ""
    writeLines(sprintf("%s & %s & %s & %s & %s & %s \\\\", lead,
                       meth_lab[[as.character(sub$method[i])]],
                       fnum(sub$mean[i]), fnum(sub$bias[i]), fnum(sub$se[i]), fnum(sub$rmse[i])), con)
  }
  if (s != tail(scen, 1)) writeLines("\\addlinespace", con)
}
writeLines(c("\\bottomrule", "\\end{tabular}", "\\end{table}"), con)
close(con)


# Figure (two panels) -----------------------------------------------------


draw <- function() {
  par(mfrow = c(1, 2), mar = c(4, 4, 2.5, 1))
  cols <- c(naive = "#B22222", eqc = "#006663", pci = "#FF6B1A")
  for (s in scen) {
    d <- long[scenario == s]
    boxplot(b2A ~ method, data = d, col = adjustcolor(cols, 0.5), outline = FALSE,
            names = meth_lab[meth_ord], ylab = expression(hat(beta)[2 * A]),
            main = scen_lab[[s]], cex.axis = 0.9)
    abline(h = truth, lty = 2, lwd = 2, col = "grey30")
  }
}
png(file.path(here, "fig_eqc_pci_mult.png"), width = 2400, height = 1200, res = 240); draw(); dev.off()
pdf(file.path(here, "fig_eqc_pci_mult.pdf"), width = 10, height = 5); draw(); dev.off()

cat("\n== multiplicative EQC vs PCI ==\n"); print(summ, digits = 3)
cat("Wrote: tab_eqc_pci_mult.tex, fig_eqc_pci_mult.{png,pdf} in ", here, "\n", sep = "")
