##----- Kaiser Causal TTE-TND
##----- Simulation study: publication-ready tables + figures
##----- Reads sim_netrisk_results.rds (from sim_netrisk_run.R) and writes:
##-----   tab_b2A.tex, tab_cif.tex   (booktabs LaTeX fragments)
##-----   fig_b2A.png/.pdf           (b2A sampling distributions by cell)
##-----   fig_cif_bias.png/.pdf      (ATT CIF confounding bias: naive vs corrected)
##-----
##----- Usage:  Rscript code/scripts/sim/sim_netrisk_report.R


library(data.table)

here <- tryCatch(dirname(sys.frame(1)$ofile), error = function(e) "code/scripts/sim")
res  <- readRDS(file.path(here, "sim_netrisk_results.rds"))
b2A  <- as.data.table(res$b2A_long)
cif  <- as.data.table(res$cif_long)
truth_b2A <- res$params$b2A
tau  <- res$params$tau

form_lab <- c(naive = "Naive (no de-biasing)", netA = "Net-risk, Option A",
              netB = "Net-risk, Option B",     CR   = "Competing risk")
est_lab  <- c(pooled = "Pooled logistic", cox_tv = "Cox, time-varying", cox_scalar = "Cox, scalar")
form_ord <- c("naive", "netA", "netB", "CR")
est_ord  <- c("pooled", "cox_tv", "cox_scalar")


# Summaries ---------------------------------------------------------------


b2A_sum <- b2A[, .(
  mean = mean(b2A), bias = mean(b2A - b2A_true),
  se = sd(b2A), rmse = sqrt(mean((b2A - b2A_true)^2)), mcse = sd(b2A) / sqrt(.N), n = .N
), by = .(formulation, estimator)]
b2A_sum[, formulation := factor(formulation, form_ord)]
b2A_sum[, estimator   := factor(estimator, est_ord)]
setorder(b2A_sum, formulation, estimator)

cif_sum <- cif[, .(
  risk1 = mean(risk1), truth1 = mean(truth1), bias1 = mean(risk1 - truth1),
  r0_naive = mean(risk0), truth0 = mean(truth0), bias0_naive = mean(risk0 - truth0),
  r0_corr = mean(risk0corr), bias0_corr = mean(risk0corr - truth0), n = .N
), by = .(formulation, estimator)]
cif_sum[, formulation := factor(formulation, c("netB", "netA", "CR"))]
setorder(cif_sum, formulation, estimator)


# LaTeX tables (booktabs) -------------------------------------------------


fnum <- function(x, d = 3) formatC(x, format = "f", digits = d)

## Table 1: b2A recovery
con <- file(file.path(here, "tab_b2A.tex"), "w")
writeLines(c(
  "% Auto-generated by sim_netrisk_report.R",
  "\\begin{table}[t]",
  "\\centering",
  sprintf("\\caption{Recovery of the causal log hazard-ratio $\\beta_{2A}$ (true value $%s$) across %d replications. Bias, empirical standard error (SE), and root mean squared error (RMSE) by de-biasing formulation and estimator.}",
          fnum(truth_b2A, 2), b2A_sum$n[1]),
  "\\label{tab:sim_b2A}",
  "\\begin{tabular}{llrrrr}",
  "\\toprule",
  "Formulation & Estimator & Mean & Bias & SE & RMSE \\\\",
  "\\midrule"), con)
for (f in form_ord) {
  sub <- b2A_sum[formulation == f]
  for (i in seq_len(nrow(sub))) {
    lead <- if (i == 1) form_lab[[f]] else ""
    writeLines(sprintf("%s & %s & %s & %s & %s & %s \\\\",
                       lead, est_lab[[as.character(sub$estimator[i])]],
                       fnum(sub$mean[i]), fnum(sub$bias[i]), fnum(sub$se[i]), fnum(sub$rmse[i])), con)
  }
  if (f != tail(form_ord, 1)) writeLines("\\addlinespace", con)
}
writeLines(c("\\bottomrule", "\\end{tabular}", "\\end{table}"), con)
close(con)

## Table 2: ATT CIF at week tau
con <- file(file.path(here, "tab_cif.tex"), "w")
writeLines(c(
  "% Auto-generated by sim_netrisk_report.R",
  "\\begin{table}[t]",
  "\\centering",
  sprintf("\\caption{Cumulative incidence among the treated (ATT) at week %d across %d replications. Observed treated risk ($\\widehat{F}_1$), and the untreated counterfactual risk ($\\widehat{F}_0$) before (naive) and after equi-confounding de-biasing, each with bias against the oracle truth.}",
          tau, cif_sum$n[1]),
  "\\label{tab:sim_cif}",
  "\\begin{tabular}{llrrr}",
  "\\toprule",
  " & & $\\widehat{F}_1$ & Naive $\\widehat{F}_0$ & Corrected $\\widehat{F}_0$ \\\\",
  "Formulation & Estimator & (bias) & (bias) & (bias) \\\\",
  "\\midrule"), con)
flev <- c("netB", "netA", "CR")
for (f in flev) {
  sub <- cif_sum[formulation == f]
  for (i in seq_len(nrow(sub))) {
    lead <- if (i == 1) form_lab[[f]] else ""
    writeLines(sprintf("%s & %s & %s (%s) & %s (%s) & %s (%s) \\\\",
                       lead, est_lab[[as.character(sub$estimator[i])]],
                       fnum(sub$risk1[i]),   fnum(sub$bias1[i]),
                       fnum(sub$r0_naive[i]),fnum(sub$bias0_naive[i]),
                       fnum(sub$r0_corr[i]), fnum(sub$bias0_corr[i])), con)
  }
  if (f != tail(flev, 1)) writeLines("\\addlinespace", con)
}
writeLines(c("\\bottomrule", "\\end{tabular}", "\\end{table}"), con)
close(con)


# Figures (base R) --------------------------------------------------------


col_est <- c(pooled = "#006663", cox_tv = "#FF6B1A", cox_scalar = "#4C4CFF")

## Figure 1: b2A sampling distributions by cell (boxplots), truth line
b2A[, cell := factor(paste(formulation, estimator, sep = "."),
                     levels = as.vector(t(outer(form_ord, est_ord, paste, sep = "."))))]
draw_fig1 <- function() {
  par(mar = c(4.5, 12, 1.5, 1))
  labs <- sapply(strsplit(levels(b2A$cell), ".", fixed = TRUE),
                 function(z) paste0(form_lab[[z[1]]], " -- ", est_lab[[z[2]]]))
  bx <- b2A[order(cell)]
  boxplot(b2A ~ cell, data = bx, horizontal = TRUE, yaxt = "n", outline = FALSE,
          col = adjustcolor(col_est[sub(".*\\.", "", levels(b2A$cell))], 0.5),
          xlab = expression(hat(beta)[2*A]), ylab = "")
  axis(2, at = seq_along(labs), labels = labs, las = 1, cex.axis = 0.8)
  abline(v = truth_b2A, lty = 2, lwd = 2, col = "grey30")
  legend("topright", legend = est_lab, fill = adjustcolor(col_est, 0.5), bty = "n", cex = 0.9)
}
png(file.path(here, "fig_b2A.png"), width = 2200, height = 1600, res = 240); draw_fig1(); dev.off()
pdf(file.path(here, "fig_b2A.pdf"), width = 9, height = 6.5); draw_fig1(); dev.off()

## Figure 2: ATT CIF confounding bias in the untreated risk (naive vs corrected), pooled
draw_fig2 <- function() {
  d <- cif_sum[estimator == "pooled" & formulation %in% c("netB", "netA", "CR")]
  d[, formulation := factor(formulation, c("netB", "netA", "CR"))]
  setorder(d, formulation)
  M <- rbind(naive = d$bias0_naive, corrected = d$bias0_corr)
  colnames(M) <- form_lab[as.character(d$formulation)]
  par(mar = c(4, 5, 1.5, 1))
  bp <- barplot(M, beside = TRUE, col = c("#B22222", "#006663"),
                ylab = expression("Bias in untreated risk  " * hat(F)[0] - F[0]),
                ylim = range(0, M) * 1.15, legend.text = c("Naive", "Corrected (EQC)"),
                args.legend = list(x = "bottomright", bty = "n"))
  abline(h = 0, lwd = 1)
}
png(file.path(here, "fig_cif_bias.png"), width = 2000, height = 1400, res = 240); draw_fig2(); dev.off()
pdf(file.path(here, "fig_cif_bias.pdf"), width = 8, height = 5.5); draw_fig2(); dev.off()


# Console echo ------------------------------------------------------------


cat("\n== b2A summary ==\n"); print(b2A_sum[, .(formulation, estimator, mean, bias, se, rmse)], digits = 3)
cat("\n== ATT CIF summary ==\n"); print(cif_sum[, .(formulation, estimator, risk1, bias1, bias0_naive, bias0_corr)], digits = 3)
cat("\nWrote: tab_b2A.tex, tab_cif.tex, fig_b2A.{png,pdf}, fig_cif_bias.{png,pdf} in ", here, "\n", sep = "")
