##----- Kaiser Causal TTE-TND
##----- Simulation study 2: EQC vs PCI under equi-confounding violation
##----- DRIVER: runs both scenarios, summarizes bias/SE/RMSE, writes table + figure
##-----
##----- Usage:  Rscript code/scripts/sim/sim_eqc_pci_run.R [N] [n_rep] [seed]
##-----
##----- Expected (true beta_2A additive hazard difference):
##-----   naive  : biased in both scenarios (unmeasured confounding);
##-----   EQC    : ~unbiased when equi-confounding holds, biased by gamma_A(b2U-b1U) when violated;
##-----   PCI    : ~unbiased in BOTH scenarios (exact under the additive-Gaussian bridge).


library(data.table)

here <- tryCatch(dirname(sys.frame(1)$ofile), error = function(e) "code/scripts/sim")
source(file.path(here, "sim_eqc_pci_functions.R"))

args  <- commandArgs(trailingOnly = TRUE)
N     <- if (length(args) >= 1) as.integer(args[1]) else 4000L
n_rep <- if (length(args) >= 2) as.integer(args[2]) else 500L
seed  <- if (length(args) >= 3) as.integer(args[3]) else 20260818L

set.seed(seed)
dgps <- c("additive", "multiplicative")
scen <- c("eqc_holds", "eqc_violated")
grid <- expand.grid(dgp = dgps, scenario = scen, stringsAsFactors = FALSE)
message(sprintf("EQC-vs-PCI simulation: N=%d, n_rep=%d x %d cells", N, n_rep, nrow(grid)))

res <- list()
t0 <- Sys.time()
pb <- txtProgressBar(min = 0, max = n_rep * nrow(grid), style = 3); k <- 0L
for (i in seq_len(nrow(grid))) {
  p <- pci_params(grid$scenario[i], grid$dgp[i])
  for (r in seq_len(n_rep)) {
    out <- tryCatch(run_pci_once(N, p), error = function(e) NULL)
    k <- k + 1L
    if (!is.null(out)) res[[length(res) + 1L]] <- cbind(rep = r, out)
    setTxtProgressBar(pb, k)
  }
}
close(pb)
cat(sprintf("\nDone in %.1f min\n", as.numeric(difftime(Sys.time(), t0, units = "mins"))))

long <- rbindlist(res)


# Summary -----------------------------------------------------------------


meth_ord <- c("naive", "eqc", "pci")
long[, method := factor(method, meth_ord)]
long[, scenario := factor(scenario, scen)]
long[, dgp := factor(dgp, dgps)]

summ <- long[, .(
  n = .N, truth = mean(truth), mean = mean(b2A),
  bias = mean(b2A - truth), se = sd(b2A), rmse = sqrt(mean((b2A - truth)^2))
), by = .(dgp, scenario, method)][order(dgp, scenario, method)]

cat("\n================ beta_2A recovery ================\n")
print(summ, digits = 3)


# LaTeX table -------------------------------------------------------------


fnum <- function(x, d = 4) formatC(x, format = "f", digits = d)
scen_lab <- c(eqc_holds = "Equi-confounding holds", eqc_violated = "Equi-confounding violated")
meth_lab <- c(naive = "Naive (no de-biasing)", eqc = "Equi-confounding", pci = "Proximal (PCI)")
dgp_lab  <- c(additive = "Additive (PCI exact)", multiplicative = "Multiplicative (PCI approximate)")
con <- file(file.path(here, "tab_eqc_pci.tex"), "w")
writeLines(c(
  "% Auto-generated by sim_eqc_pci_run.R",
  "\\begin{table}[t]", "\\centering",
  sprintf("\\caption{Recovery of the causal effect $\\beta_{2A}$ over %d replications, when equi-confounding holds and when it is violated, under additive (exact proximal identification) and multiplicative (approximate) hazards. Under equi-confounding violation the proximal estimator stays near-unbiased while the equi-confounding estimator does not; the true $\\beta_{2A}$ differs by hazard scale (additive difference vs.\\ log hazard-ratio).}", n_rep),
  "\\label{tab:sim_eqc_pci}",
  "\\begin{tabular}{lllrrrr}", "\\toprule",
  "Hazards & Scenario & Method & Truth & Bias & SE & RMSE \\\\", "\\midrule"), con)
for (dd in dgps) {
  for (s in scen) {
    sub <- summ[dgp == dd & scenario == s]
    for (i in seq_len(nrow(sub))) {
      lead_d <- if (s == scen[1] && i == 1) dgp_lab[[dd]] else ""
      lead_s <- if (i == 1) scen_lab[[s]] else ""
      writeLines(sprintf("%s & %s & %s & %s & %s & %s & %s \\\\", lead_d, lead_s,
                         meth_lab[[as.character(sub$method[i])]],
                         fnum(sub$truth[i]), fnum(sub$bias[i]), fnum(sub$se[i]), fnum(sub$rmse[i])), con)
    }
    writeLines("\\addlinespace", con)
  }
  if (dd != tail(dgps, 1)) writeLines("\\midrule", con)
}
writeLines(c("\\bottomrule", "\\end{tabular}", "\\end{table}"), con)
close(con)


# Figure: 2 x 2 (rows = hazard model, cols = scenario) --------------------


draw <- function() {
  par(mfrow = c(2, 2), mar = c(3.5, 4, 3, 1))
  cols <- c(naive = "#B22222", eqc = "#006663", pci = "#FF6B1A")
  for (dd in dgps) {
    truth <- pci_params("eqc_holds", dd)$b2A
    for (s in scen) {
      d <- long[dgp == dd & scenario == s]
      boxplot(b2A ~ method, data = d, col = adjustcolor(cols, 0.5), outline = FALSE,
              names = meth_lab[meth_ord], ylab = expression(hat(beta)[2 * A]),
              main = sprintf("%s -- %s", dgp_lab[[dd]], scen_lab[[s]]),
              cex.axis = 0.85, cex.main = 0.85)
      abline(h = truth, lty = 2, lwd = 2, col = "grey30")
    }
  }
}
png(file.path(here, "fig_eqc_pci.png"), width = 2600, height = 2000, res = 220); draw(); dev.off()
pdf(file.path(here, "fig_eqc_pci.pdf"), width = 11, height = 8.5); draw(); dev.off()

saveRDS(list(long = long, summary = summ, N = N, n_rep = n_rep, seed = seed),
        file.path(here, "sim_eqc_pci_results.rds"))
cat("Wrote: tab_eqc_pci.tex, fig_eqc_pci.{png,pdf}, sim_eqc_pci_results.rds in ", here, "\n", sep = "")
